### ISSUE TITLE
Flesh out yaml data

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#6]
We need to add content to and cross check the content of `data.yaml`. This includes:
1. Syncing with the working copy of the google sheet.
2. Adding content from [table.md](https://github.com/LSSTDESC/LSSTDarkMatter/blob/master/table.md)

**Comment by kadrlica** [comment]
@yymao we should add descriptions for the categories themselves (i.e., Models, Probes, Measurements, Targets). Would it be better to do this in the `Categories` section -- i.e.,
```
Categories:
  - Models
      description: A "model" is a theoretical framework describing the physical mechanism governing the microphysics of dark matter.  Examples: warm dark matter, axion dark matter, primordial black hole dark matter, etc. 
  - Probes
  - Measurements
  - Targets
```
 or in the individual section for each category -- i.e.
```
Models:
  description: A "model" is a theoretical framework describing the physical mechanism governing the microphysics of dark matter.  Examples: warm dark matter, axion dark matter, primordial black hole dark matter, etc.
  - key: wdm
    label: Warm dark matter
    description: >-
      Dark matter that acts like a thermal particle                                  
      with mass less than 1 GeV.
...
```

**Comment by johannct** [comment]
Probably in Categories, if each category instance already has description levels. What else could be added within the Categories block?

**Comment by yymao** [comment]
Yes, should put in the Categories section. Should format similarly as the nodes, i.e.:
```
Categories:
  - label: Models
    description: A "model" is a theoretical framework describing the physical mechanism governing the microphysics of dark matter.  Examples: warm dark matter, axion dark matter, primordial black hole dark matter, etc. 
  - label: Probes
```

**Comment by kadrlica** [comment]
I've updated the `Categories` section to mirror other nodes:
```
Categories:
  - key: models
    label: Models
    description: >-
      A "model" is a theoretical framework describing the physical                   
      mechanism governing the microphysics of dark matter.  Examples:                
      warm dark matter, axion dark matter, primordial black hole dark                
      matter, etc.
```
@johannct other elements of the `Categories` section could define appearance (i.e., color, fontsize, etc.) or additional content (we imagine the description as a mouse-over tooltip, but we may want to add more).

**Comment by yymao** [comment]
@kadrlica should we then use the `key` field in the rest of the yaml file? i.e., 

```yaml
models: 
  - key: sidm
  #...
probes:
  #...
```
